/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcContainer {
    }
    interface IcLogin {
        "name2": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIcContainerElement extends Components.IcContainer, HTMLStencilElement {
    }
    var HTMLIcContainerElement: {
        prototype: HTMLIcContainerElement;
        new (): HTMLIcContainerElement;
    };
    interface HTMLIcLoginElement extends Components.IcLogin, HTMLStencilElement {
    }
    var HTMLIcLoginElement: {
        prototype: HTMLIcLoginElement;
        new (): HTMLIcLoginElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ic-container": HTMLIcContainerElement;
        "ic-login": HTMLIcLoginElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IcContainer {
    }
    interface IcLogin {
        "name2"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ic-container": IcContainer;
        "ic-login": IcLogin;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ic-container": LocalJSX.IcContainer & JSXBase.HTMLAttributes<HTMLIcContainerElement>;
            "ic-login": LocalJSX.IcLogin & JSXBase.HTMLAttributes<HTMLIcLoginElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
